// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiRestauranteT.Datos;

#nullable disable

namespace WebApiRestauranteT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231101010933_CreacioTabla")]
    partial class CreacioTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiRestauranteT.Models.Mesa", b =>
                {
                    b.Property<int>("idMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idMesa"));

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.HasKey("idMesa");

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            idMesa = 1,
                            estado = false
                        },
                        new
                        {
                            idMesa = 2,
                            estado = false
                        },
                        new
                        {
                            idMesa = 3,
                            estado = false
                        },
                        new
                        {
                            idMesa = 4,
                            estado = false
                        },
                        new
                        {
                            idMesa = 5,
                            estado = false
                        },
                        new
                        {
                            idMesa = 6,
                            estado = false
                        });
                });

            modelBuilder.Entity("WebApiRestauranteT.Models.Orden", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("estado")
                        .HasColumnType("bit");

                    b.Property<int>("idMesa")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("WebApiRestauranteT.Models.Plato", b =>
                {
                    b.Property<int>("idPlato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPlato"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("precio")
                        .HasColumnType("float");

                    b.HasKey("idPlato");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            idPlato = 1,
                            nombre = "Chaulafan",
                            precio = 4.5
                        },
                        new
                        {
                            idPlato = 2,
                            nombre = "Mixto",
                            precio = 6.0
                        });
                });

            modelBuilder.Entity("WebApiRestauranteT.Models.PlatoOrden", b =>
                {
                    b.Property<int>("idPlatoOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idPlatoOrden"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("idPlato")
                        .HasColumnType("int");

                    b.HasKey("idPlatoOrden");

                    b.ToTable("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
